### ISSUE TITLE
Can't load /usr/share/easy-rsa/pki/.rnd into RNG

### ISSUE THREAD

**Issue by Scinawa** [OpenVPN/easy-rsa#261]
Hi, 
we get the following error build calling ./easyrsa build-ca.
We tried both with the updated debian version of the package, and the current master version of the repo.
Here is the full process..
```
root@tunnel:/usr/share# apt install easy-rsa
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following NEW packages will be installed:
  easy-rsa
0 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.
Need to get 0 B/35.1 kB of archives.
After this operation, 95.2 kB of additional disk space will be used.
Selecting previously unselected package easy-rsa.
(Reading database ... 134249 files and directories currently installed.)
Preparing to unpack .../easy-rsa_3.0.4-2_all.deb ...
Unpacking easy-rsa (3.0.4-2) ...
Setting up easy-rsa (3.0.4-2) ...
Processing triggers for man-db (2.8.4-2+b1) ...
root@tunnel:/usr/share# cd easy-rsa/
root@tunnel:/usr/share/easy-rsa# ./easyrsa init-pki

init-pki complete; you may now create a CA or requests.
Your newly created PKI dir is: /usr/share/easy-rsa/pki

root@tunnel:/usr/share/easy-rsa# ./easyrsa build-ca
Can't load /usr/share/easy-rsa/pki/.rnd into RNG
140276608762304:error:2406F079:random number generator:RAND_load_file:Cannot open file:../crypto/rand/randfile.c:88:Filename=/usr/share/easy-rsa/pki/.rnd
Generating a RSA private key
...................................................................+++++
......................................................+++++
writing new private key to '/usr/share/easy-rsa/pki/private/ca.key.JuUJZIfT6B'
Enter PEM pass phrase:
140276608762304:error:2807106B:UI routines:UI_process:processing error:../crypto/ui/ui_lib.c:543:while reading strings
140276608762304:error:0906406D:PEM routines:PEM_def_callback:problems getting password:../crypto/pem/pem_lib.c:59:
140276608762304:error:0907E06F:PEM routines:do_pk8pkey:read key:../crypto/pem/pem_pk8.c:83:

```

**Comment by ecrist** [comment]
Have you tried downloading the 3.0.5 release?

Eric Crist

**Comment by Scinawa** [comment]
Hi!
Thanks for the quick answer. Yes: here is the output

```
  inflating: easy-rsa-3.0.5/release-keys/README.md  
root@tunnel:/usr/share/easy-rsa_github# cd easy-rsa-3.0.5/
root@tunnel:/usr/share/easy-rsa_github/easy-rsa-3.0.5# cp /home/scinawa/vars .
root@tunnel:/usr/share/easy-rsa_github/easy-rsa-3.0.5# cp vars easyrsa3/
root@tunnel:/usr/share/easy-rsa_github/easy-rsa-3.0.5# cd easyrsa3/
root@tunnel:/usr/share/easy-rsa_github/easy-rsa-3.0.5/easyrsa3# ./easyrsa init-pki
root@tunnel:/usr/share/easy-rsa_github/easy-rsa-3.0.5/easyrsa3# ./easyrsa build-ca
Enter New CA Key Passphrase: 
root@tunnel:/usr/share/easy-rsa_github/easy-rsa-3.0.5/easyrsa3# ./easyrsa build-ca nopass
Generating RSA private key, 2048 bit long modulus (2 primes)
........+++++
............+++++
e is 65537 (0x010001)
Can't load /usr/share/easy-rsa_github/easy-rsa-3.0.5/easyrsa3/pki/.rnd into RNG
140199901626816:error:2406F079:random number generator:RAND_load_file:Cannot open file:../crypto/rand/randfile.c:88:Filename=/usr/share/easy-rsa_github/easy-rsa-3.0.5/easyrsa3/pki/.rnd
root@tunnel:/usr/share/easy-rsa_github/easy-rsa-3.0.5/easyrsa3# openssl version
OpenSSL 1.1.1  11 Sep 2018

```

**Comment by numericOverflow** [comment]
I've got the same issue.  Using OpenSSL 1.1.1 with easyRSA 3.0.5 on Ubuntu 18,04.1 LTS

```
root@server:/etc/easyRSA# EASYRSA_PKI=intermediateCA ./easyrsa sign-req webserver cert.local
Note: using Easy-RSA configuration from: ./vars
Using SSL: openssl OpenSSL 1.1.1  11 Sep 2018

You are about to sign the following certificate.
Please check over the details shown below for accuracy. Note that this request
has not been cryptographically verified. Please be sure it came from a trusted
source or that you have verified the request checksum with the sender.

Request subject, to be signed as a webserver certificate for 36500 days:
subject=
    commonName                = cert.local

Type the word 'yes' to continue, or any other input to abort.
  Confirm request details: yes
Using configuration from ./safessl-easyrsa.cnf
Can't load intermediateCA/.rnd into RNG
Enter pass phrase for intermediateCA/private/ca.key:
...
...
```

**Comment by polynomialspace** [comment]
Removing the following line at the beginning of `pki/openssl-easyrsa.cnf` seems to resolve the issue:

`RANDFILE                = $ENV::EASYRSA_PKI/.rnd`


I'm not sure the rationale for why it is being overridden here. Alternatively you could [manually create .rnd](https://security.stackexchange.com/a/177512).

cc: #263

**Comment by ecrist** [comment]
This is related to newer versions of OpenSSL configuration files.  I'll get this fixed in v3.0.6 in the next week or so.

**Comment by ecrist** [comment]
Yeah, I forgot.  Sorry.  It'll be in v3.0.7 which will be a fast-follow release, I hope.

**Comment by codebling** [comment]
@ecrist or any other member, is there any chance we could get a new release with this fix?  Is one planned?

**Comment by ecrist** [comment]
Yeah, summer is over, I’m out of excuses.  I’ll get to work on it.

Eric

**Comment by es3** [comment]
# Create a random file
dd if=/dev/urandom of=pki/.rnd bs=256 count=1

# And Build Ca
./easyrsa build-ca

**Comment by theAkito** [comment]
On easy-rsa 3.0.6 :

```
140689697488200:error:2406F079:random number generator:RAND_load_file:Cannot open file:crypto/rand/randfile.c
```

I need this urgently for a low entropy cloud, to speed up bulk cert generation.

I solved this error by fixing another error, where `cp` wasn't copying the manually created `.rnd` file correctly. Busybox has a light `cp` version. Had to replace it with `rsync`.

> Yeah, summer is over, I’m out of excuses. I’ll get to work on it.

**Comment by ecrist** [comment]
What are the differences between the busybox cp and what we're using?

**Comment by theAkito** [comment]
@ecrist 

Well, I was using the busybox `cp` manually, in a script.
Busybox tries to be as tiny as reasonably possible. Therefore the standard tools one is used to are limited to basic functionality. For example, the busybox `cp` can't follow symlinks, because the option is just not available.

**Comment by ecrist** [comment]
I see.  I don't think we're going to chase the oddity that is busybox in the manner.

This issue is closed, and is fixed in the unreleased v3.0.7.  I'll try to get a release pushed out this evening.

**Comment by Kaju-Bubanja** [comment]
This is still happenening for me.

**Comment by ecrist** [comment]
I just don’t know if it’s worth the effort fixing this in busybox.  Hardly makes sense that their cp utility is limited in function but rsync is available.  We will not be using rsync within easy-rsa at this time.

Eric F Crist

**Comment by theAkito** [comment]
> Hardly makes sense that their cp utility is limited in function but rsync is available.

I guess, busybox tries to use many different tools on a basic level. That results in `rsync` being available, when `cp` is only basic.

That said, how would you define a bug worth fixing? I think it depends on how likely you are impacted by it (in theory) and how many people are how much impacted by it (in practice). We have several people here struggling with this issue.
Doesn't that already make it worth fixing?

**Comment by ecrist** [comment]
If we start using rsync, then I have to ship rsync on Windows, too.  The Windows user base of EasyRSA is far greater than that of busybox.  Maybe you manage an open source project larger than EasyRSA and you're speaking from experience, but I've found it is nearly impossible to make everyone happy.  If you have suggestions, I'm all ears.  

Maybe don't use symlinks?

**Comment by theAkito** [comment]
@ecrist 

I don't see it black and white like that. It's not a question of "use this or use that". There is a lot of software that has exceptions and compatability modes, that you can enable when running them, even though these modes are used by maybe 0.1% of all users.
If we take this fact as an example, there could be for example a switch for that, which allows using `rsync` for compatability reasons. If it is not needed, then nothing will change about EasyRSA from a user's perspective.

Isn't this or something similar worth considering?

**Comment by ecrist** [comment]
It adds test paths. I'm not entertaining this further. 

Eric Crist

**Comment by codebling** [comment]
Understand if this won't receive a fix, but just to clarify, I thought this was fixed in 3.0.7? 

I can't find any commits specifically mentioning the issue, but I'd like to understand if a fix was made and that fix revealed that there is an additional problem (the fix never fully resolved the issue), or if a fix was made and it resolved the issue for some people but others are still experiencing the issue due to a separate problem. 

(Sorry to add to the chatter)

**Comment by ecrist** [comment]
I don’t believe this was ever fixed.  I see my comment about a fix in 3.0.7, but I cannot find a commit, either.

Eric F Crist

**Comment by TinCanTech** [comment]
This was an `openssl` issue which was not addressed by `easyrsa` because it was not necessary to do so.

**Comment by codebling** [comment]
Ok, thanks for the info. 

I'm seeing suggestions that this may be: 
 * [related to a change in OpenSSL config](https://github.com/OpenVPN/easy-rsa/issues/261#issuecomment-447702334), or
 * to do with a kludgy `busybox cp` implementation


If this is related to an OpenSSL config change, it might be worth fixing. As suggested [in one of the earlier comments](https://github.com/OpenVPN/easy-rsa/issues/261#issuecomment-444408090), the fix may be as simple as removing a line from [`openssl-easyrsa.cnf`](https://github.com/OpenVPN/easy-rsa/blob/master/easyrsa3/openssl-easyrsa.cnf). 

If this is related to a quirk in `busybox cp` (which, tbh, seems unlikely), I'm definitely ok with not fixing it (though it may be an indication that the use of `cp` is too closely tied with the shell implementation, which would also be bad). 

I've done some testing, I am not currently able to reproduce. It's also possible that this is no longer an issue. It might also make sense to lock this conversation with a comment asking users still encountering this to open a new issue with some basic info (e.g. what easy-rsa version and environment) and a minimally reproducible example (possible that @Kaju-Bubanja is on an old version?).

**Comment by ecrist** [comment]
Locking this conversation.  Please open a new issue if problems persist.
