### ISSUE TITLE
Can't open /root/easy-rsa/pki/index.txt.attr for reading, No such file or directory

### ISSUE THREAD

**Issue by aix4c** [OpenVPN/easy-rsa#262]
steps to reproduce:
easyrsa init-pki
easyrsa build-ca
easyrsa gen-req EntityName
easyrsa sign-req server

Type the word 'yes' to continue, or any other input to abort.
  Confirm request details: yes
Using configuration from /root/easy-rsa/safessl-easyrsa.cnf
Can't open /root/easy-rsa/pki/index.txt.attr for reading, No such file or directory
140156985258496:error:02001002:system library:fopen:No such file or directory:crypto/bio/bss_file.c:72:fopen('/root/easy-rsa/pki/index.txt.attr','r')
140156985258496:error:2006D080:BIO routines:BIO_new_file:no such file:crypto/bio/bss_file.c:79:
Check that the request matches the signature
Signature ok
The Subject's Distinguished Name is as follows
commonName            :ASN.1 12:'zzz'
HU:invalid type in 'policy' configuration

Easy-RSA error:

signing failed (openssl output above may have more detail)

**Comment by xavierba** [comment]
Just a drive-by comment.
```Can't open /root/easy-rsa/pki/index.txt.attr for reading, No such file or directory``` is fixed by #241, this error is not fatal.
I have no idea about ```HU:invalid type in 'policy' configuration```. I cannot reproduce, so this is probably something in your ```openssl-easyrsa.cnf```

**Comment by ecrist** [comment]
This doesn't appear to be happening any longer.

**Comment by luizluca** [comment]
@ecrist , it still happens with openssl 1.1.x with master (38c42b2). It should not be closed as WORKSFORME.

#241 was just rebased to master. It fixes the warn
