### ISSUE TITLE
Travis CI always returns success for unit tests

### ISSUE THREAD

**Issue by TinCanTech** [OpenVPN/easy-rsa#355]
Blame: `op_test.sh`

**Comment by ecrist** [comment]
This has been fixed, right?  Just needs to be closed?

**Comment by TinCanTech** [comment]
`op_test.sh` is currently still broken but this does not effect any releases.
